import pptxgen from "pptxgenjs"

const COLORS = {
    primary: "1E40AF",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
    accent: "D97706"
};

export const generatePpt = async (data) => {
    const ppt = new pptxgen()
    ppt.layout = "LAYOUT_WIDE"
    ppt.author = "CortexAI"
    ppt.title = data.title || "Situation Briefing"
    ppt.subject = data.title || "Disaster Response Briefing"
    ppt.company = "CortexAI"
    ppt.theme = {
        headFontFace: "Arial",
        bodyFontFace: "Arial"
    }

    addCover(ppt, data)

    data?.slides?.forEach((s, i) => {
        addContentSlide(
            ppt,
            s.title || `Slide ${i + 1}`,
            s.points || [],
            s.speakerNotes || "",
            s.dataVisualRecommendation || "",
            i + 1,
            data.slides.length
        )
    });

    addThankYou(ppt, data)

    return ppt
}

const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = {
        color: COLORS.primary
    }

    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: { color: "60A5FA" },
        line: { color: "60A5FA" }
    })

    slide.addText(data.title || "Disaster Situation Briefing", {
        x: 0.7,
        y: 1.7,
        w: 12,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
    })

    if (data.subtitle) {
        slide.addText(data.subtitle, {
            x: 1,
            y: 2.8,
            w: 11.5,
            h: 0.4,
            align: "center",
            color: "DBEAFE",
            fontSize: 15,
        })
    }

    slide.addText("Generated by CortexAI Response Platform", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10,
    })
}

function addContentSlide(
    ppt,
    title,
    points,
    speakerNotes,
    dataVisualRecommendation,
    page,
    total
) {
    const slide = ppt.addSlide();
    slide.background = { color: COLORS.white };

    // Slide Header
    slide.addText(title, {
        x: 0.6,
        y: 0.35,
        w: 10,
        h: 0.4,
        fontSize: 22,
        bold: true,
        color: COLORS.primary,
    });

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.85,
        w: 12,
        h: 0,
        line: { color: COLORS.border, width: 1.2 },
    });

    // Content Points
    const visiblePoints = (Array.isArray(points) ? points : []).slice(0, 5);
    visiblePoints.forEach((point, i) => {
        const y = 1.1 + i * 0.7;

        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.55,
            fill: { color: i % 2 ? "F8FAFC" : "EFF6FF" },
            line: { color: COLORS.border },
            radius: 0.08,
        });

        slide.addText(point, {
            x: 0.9,
            y: y + 0.08,
            w: 11.5,
            h: 0.38,
            fontSize: 13,
            color: COLORS.text,
            fit: "shrink",
        });
    });

    // Data / Visual Recommendation Banner (if present)
    if (dataVisualRecommendation) {
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y: 4.8,
            w: 12,
            h: 0.6,
            fill: { color: "FEF3C7" },
            line: { color: "F59E0B" },
            radius: 0.06
        });
        slide.addText(`Visual / Chart Recommendation: ${dataVisualRecommendation}`, {
            x: 0.9,
            y: 4.85,
            w: 11.5,
            h: 0.5,
            fontSize: 11,
            color: "92400E",
            bold: true
        });
    }

    // Speaker Notes Footer Box
    if (speakerNotes) {
        slide.addText(`Speaker Notes: ${speakerNotes}`, {
            x: 0.7,
            y: 5.6,
            w: 12,
            h: 0.8,
            fontSize: 10,
            color: COLORS.muted,
            italic: true
        });
    }

    // Pagination
    slide.addText(`${page}/${total}`, {
        x: 12.1,
        y: 6.9,
        w: 0.8,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted,
    });

    slide.addText(`CortexAI Grounded Intelligence`, {
        x: 0.6,
        y: 6.9,
        w: 4,
        h: 0.2,
        fontSize: 10,
        color: COLORS.muted,
    });
}

const addThankYou = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = { color: COLORS.secondary };

    slide.addText(`Briefing Concluded`, {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 32,
        bold: true,
    });

    if (data.citations && data.citations.length > 0) {
        slide.addText(`Grounded in Source Citations: ${data.citations.join(", ")}`, {
            x: 1,
            y: 3.2,
            w: 11.33,
            h: 0.6,
            align: "center",
            color: "94A3B8",
            fontSize: 12,
        });
    }

    slide.addText(`Generated by CortexAI`, {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });
}
