import PDFDocument from "pdfkit"

export const generatePdf = async (data, docType = "document") => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "CortexAI",
                Title: data.title || (docType === "advisory" ? "Disaster Advisory" : "Executive Summary"),
                Creator: "CortexAI"
            }
        })

        const chunks = []
        doc.on("data", (chunk) => chunks.push(chunk))
        doc.on("end", () => resolve(Buffer.concat(chunks)))
        doc.on("error", reject)

        const title = data.title || (docType === "advisory" ? "URGENT SITUATION ADVISORY" : "EXECUTIVE SUMMARY")

        // Title
        doc
            .fontSize(22)
            .text(title, { align: "center" })
            .fillColor("#111827")

        if (data.date) {
            doc.moveDown(0.3)
            doc.fontSize(10).text(`Date: ${data.date}`, { align: "center" }).fillColor("#6B7280")
        }

        doc.moveDown(1.5)

        if (docType === "advisory") {
            const fields = [
                { label: "Situation Overview", value: data.situation },
                { label: "Affected Audience / Region", value: data.affectedAudience },
                { label: "Risk & Impact Assessment", value: data.riskImpact },
                { label: "Recommended Actions", value: data.recommendedAction },
                { label: "Contact & Assistance Details", value: data.contactDetails }
            ]

            fields.forEach(f => {
                if (f.value) {
                    doc.fontSize(14).text(f.label).fillColor("#1E40AF")
                    doc.moveDown(0.3)
                    doc.fontSize(11).text(f.value, { lineGap: 3 }).fillColor("#374151")
                    doc.moveDown(1)
                }
            })
        } else if (docType === "executiveSummary" || docType === "executivesummary") {
            if (data.context) {
                doc.fontSize(14).text("Context & Overview").fillColor("#1E40AF")
                doc.moveDown(0.3)
                doc.fontSize(11).text(data.context, { lineGap: 3 }).fillColor("#374151")
                doc.moveDown(1)
            }

            const listSections = [
                { label: "Key Facts & Data Points", items: data.keyFacts },
                { label: "Strategic Implications", items: data.implications },
                { label: "Key Risks Identified", items: data.risks },
                { label: "Action Recommendations", items: data.recommendations }
            ]

            listSections.forEach(sec => {
                if (sec.items && sec.items.length > 0) {
                    doc.fontSize(14).text(sec.label).fillColor("#1E40AF")
                    doc.moveDown(0.3)
                    sec.items.forEach(item => {
                        doc.fontSize(11).text(`• ${item}`, { lineGap: 3 }).fillColor("#374151")
                    })
                    doc.moveDown(1)
                }
            })

            if (data.decisionRequired) {
                doc.fontSize(14).text("Decision Required").fillColor("#B91C1C")
                doc.moveDown(0.3)
                doc.fontSize(11).text(data.decisionRequired, { lineGap: 3 }).fillColor("#374151")
                doc.moveDown(1)
            }
        } else {
            // Generic sections fallback
            if (data.sections) {
                data.sections.forEach(s => {
                    doc.fontSize(14).text(s.heading).fillColor("#111827")
                    doc.moveDown(0.3)
                    if (Array.isArray(s.points)) {
                        s.points.forEach(p => {
                            doc.fontSize(11).text(`• ${p}`, { lineGap: 3 }).fillColor("#374151")
                        })
                    } else if (s.content) {
                        doc.fontSize(11).text(s.content, { lineGap: 3 }).fillColor("#374151")
                    }
                    doc.moveDown(1)
                })
            }
        }

        // Citations Footer
        if (data.citations && data.citations.length > 0) {
            doc.moveDown(1)
            doc.fontSize(9).text(`Source Citations: ${data.citations.join(", ")}`, { align: "left" }).fillColor("#9CA3AF")
        }

        doc.moveDown(1)
        doc.fontSize(9).text("Generated by CortexAI Disaster Communications Engine", { align: "center" }).fillColor("#9CA3AF")

        doc.end()
    })
}
